// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------
namespace BundlerMinifierVsix
{
    static class Vsix
    {
        public const string Id = "a0ae318b-4f07-4f71-93cb-f21d3f03c6d3";
        public const string Name = "Bundler & Minifier";
        public const string Description = @"Adds support for bundling and minifying JavaScript, CSS and HTML files in any project.";
        public const string Language = "en-US";
        public const string Version = "2.3.1";
        public const string Author = "Mads Kristensen";
        public const string Tags = "bundle, bundling, minify, minification, js, css, html";
    }
}
