// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.211
// </auto-generated>
// ------------------------------------------------------------------------------
namespace BundlerMinifierVsix
{
    static class Vsix
    {
        public const string Id = "5783ce1f-b23d-4e84-87a4-6b2cbe9e0602";
        public const string Name = "Bundler & Minifier";
        public const string Description = @"Adds support for bundling and minifying JavaScript, CSS and HTML files in any project.";
        public const string Language = "en-US";
        public const string Version = "3.3";
        public const string Author = "Jason Moore";
        public const string Tags = "bundle, bundling, minify, minification, js, css, html";
    }
}
