//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BundlerMinifierVsix.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BundlerMinifierVsix.Resources.Text", typeof(Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generated.
        /// </summary>
        internal static string AdornmentGenerated {
            get {
                return ResourceManager.GetString("AdornmentGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to toggle visibility.
        /// </summary>
        internal static string AdornmentTooltip {
            get {
                return ResourceManager.GetString("AdornmentTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bundle and Minify Files.
        /// </summary>
        internal static string ButtonBundle {
            get {
                return ResourceManager.GetString("ButtonBundle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minify File.
        /// </summary>
        internal static string ButtonMinify {
            get {
                return ResourceManager.GetString("ButtonMinify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-bundle File.
        /// </summary>
        internal static string ButtonReBundle {
            get {
                return ResourceManager.GetString("ButtonReBundle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-minify File.
        /// </summary>
        internal static string ButtonReMinify {
            get {
                return ResourceManager.GetString("ButtonReMinify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is an error in the {0} file. This could be due to a change in the format after this extension was updated.
        /// </summary>
        internal static string ErrorConfigFile {
            get {
                return ResourceManager.GetString("ErrorConfigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error minifying {0}. See Error List for details.
        /// </summary>
        internal static string ErrorMinifying {
            get {
                return ResourceManager.GetString("ErrorMinifying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not update {0}. Make sure it&apos;s not write-protected or has syntax errors.
        /// </summary>
        internal static string ErrorRemoveBundle {
            get {
                return ResourceManager.GetString("ErrorRemoveBundle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to install the {0} NuGet package.
        /// </summary>
        internal static string NugetErrorInstalling {
            get {
                return ResourceManager.GetString("NugetErrorInstalling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to ininstall the {0} NuGet package.
        /// </summary>
        internal static string NugetErrorUninstalling {
            get {
                return ResourceManager.GetString("NugetErrorUninstalling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished installing the {0} NuGet package.
        /// </summary>
        internal static string NugetFinishedInstalling {
            get {
                return ResourceManager.GetString("NugetFinishedInstalling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished uninstalling the {0} NuGet package.
        /// </summary>
        internal static string NugetFinishedUninstalling {
            get {
                return ResourceManager.GetString("NugetFinishedUninstalling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing {0} NuGet package, this may take a minute....
        /// </summary>
        internal static string NugetInstalling {
            get {
                return ResourceManager.GetString("NugetInstalling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A NuGet package will be installed to augment the MSBuild process, but no files will be added to the project.
        ///
        ///This may require an internet connection.
        ///
        ///Do you want to continue?.
        /// </summary>
        internal static string NugetInstallPrompt {
            get {
                return ResourceManager.GetString("NugetInstallPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstalling {0} NuGet package, this may take a minute....
        /// </summary>
        internal static string NugetUninstalling {
            get {
                return ResourceManager.GetString("NugetUninstalling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will remove the file from {0}.
        ///
        ///Do you want to continue?.
        /// </summary>
        internal static string promptRemoveBundle {
            get {
                return ResourceManager.GetString("promptRemoveBundle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bundle created.
        /// </summary>
        internal static string StatusBundleCreated {
            get {
                return ResourceManager.GetString("StatusBundleCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bundle updated.
        /// </summary>
        internal static string statusBundleUpdated {
            get {
                return ResourceManager.GetString("statusBundleUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating bundle.
        /// </summary>
        internal static string StatusCreatingBundle {
            get {
                return ResourceManager.GetString("StatusCreatingBundle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} minified.
        /// </summary>
        internal static string StatusMinified {
            get {
                return ResourceManager.GetString("StatusMinified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean all output files.
        /// </summary>
        internal static string TaskCleanOutputFilesDescription {
            get {
                return ResourceManager.GetString("TaskCleanOutputFilesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean output files.
        /// </summary>
        internal static string TaskCleanOutputFilesName {
            get {
                return ResourceManager.GetString("TaskCleanOutputFilesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bundle configs specified in {0}.
        /// </summary>
        internal static string TaskUpdateAllFilesDescription {
            get {
                return ResourceManager.GetString("TaskUpdateAllFilesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update all files.
        /// </summary>
        internal static string TaskUpdateAllFilesName {
            get {
                return ResourceManager.GetString("TaskUpdateAllFilesName", resourceCulture);
            }
        }
    }
}
